data_ingestion:
  workspace: "ntchindagiscard"
  project: "id-card-information"
  version: 1
  dataset: "yolov12"

model_trainer:
  model: "yolo12x"
  epochs: 200
  batch: 32
  imgsz: 640
  device: "0,1,2,3"
  scale: 0.9
  mixup: 0.0