data_ingestion:
  workspace: "ntchindagiscard"
  project: "id_card_annotation"
  version: 1
  dataset: "yolov8"

model_trainer:
  data: "id_card_annotation-1"
  model: "yolov8n.pt"
  epochs: 100
  batch: 8
  imgsz: 320
  device: 0
  scale: 0.9
  mixup: 0.0