data_ingestion:
  workspace: "ntchindagiscard"
  project: "id-card-information"
  version: 1
  dataset: "yolov8"

model_trainer:
  data: "id-card-information-1"
  model: "yolov8n.pt"
  epochs: 200
  batch: 32
  imgsz: 640
  device: "cpu"
  scale: 0.9
  mixup: 0.0